# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.6.0-123-g098bef9
_src_path: https://github.com/usnistgov/cookiecutter-nist-python.git
command_line_interface: argparse
conda_channel: conda-forge
email: wpk@nist.gov
full_name: William P. Krekelberg
github_username: usnistgov
project_name: open-notebook
project_short_description: Command line program to open jupyter notebooks from single
    server
project_slug: open_notebook
pypi_username: wpk-nist
sphinx_theme: sphinx_book_theme
sphinx_use_autodocsumm: true
year: '2023'
